---
codecov:
  require_ci_to_pass: false
component_management:
  individual_components:
    - component_id: proxy
      name: proxy
      paths:
        - packages/proxy/bin/**
        - packages/proxy/src/**
    - component_id: config-default
      name: config-default
      paths:
        - packages/config-default/src/**
flags:
  config-default:
    carryforward: true
    paths:
      - packages/config-default/
  proxy:
    carryforward: true
    paths:
      - packages/proxy/
